### ISSUE TITLE
How to customize multiple outfits

### ISSUE THREAD

**Issue by ChenZongHeng** [avatarsdk/samples-js#1]
Hello, may I ask how I can customize more character costumes? avatarsdk only provides three sets of clothes for men and women, I want to provide 10 sets of clothes for men and women, how can I customize them?

**Comment by ilardm** [comment]
Hello, you should contact support@avatarsdk.com for custom outfits import.
Also please check out https://metaperson.avatarsdk.com there are available additional set of outfits.

**Comment by ilardm** [comment]
Hello, you should contact [support@avatarsdk.com](mailto:support@avatarsdk.com) for custom outfits import.
Also please check out https://metaperson.avatarsdk.com/ there are available additional set of outfits.
